---
name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:

  build:
    name: Build the lib with Idris2 HEAD
    runs-on: ubuntu-latest-4core
    env:
      PACK_DIR: /root/.pack
    strategy:
      fail-fast: false
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: Export IDRIS2_ASYNC_THREADS Environment Variable
        run: |
          echo "IDRIS2_ASYNC_THREADS=4" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install lsm-rrbvctor
        run: pack --no-prompt install lsm-rrbvector
      - name: Build lsm-rrbvector
        run: pack typecheck lsm-rrbvector
      - name: Test lsm-rrbvector
        run: pack --no-prompt test lsm-rrbvector
